cover_image: images/Mcr-Coderdojo-12_55-small-653x576.webp
modified: '2014-07-13T00:00:00'
published: '2014-07-13T00:00:00'
tags:
- events
thumbnail: images/Mcr-Coderdojo-12_55-small-653x576_thumb.webp
title: '#15: July 2014'
