author: Anthony Harrison
modified: '2014-10-16T23:14:30'
published: '2014-10-16T23:14:30'
slug: resources-to-help-learn-the-basics-of-coding
tags: []
title: Resources to help learn the basics of Coding
