author: Lisa Brown
cover_image: images/DSC06736-2.webp
modified: '2023-04-09T16:35:14'
published: '2023-04-09T16:35:14'
thumbnail: images/DSC06736-2_thumb.webp
title: Reflecting on 10 Years of Manchester CoderDojo
