cover_image: images/eveningnews-1038x576.webp
modified: '2015-07-12T00:00:00'
published: '2015-07-12T00:00:00'
tags:
- events
thumbnail: images/eveningnews-1038x576_thumb.webp
title: '#24: Sunday 12th July 2015'
