author: Tom Clarke
cover_image: images/DM16AngelSq_MainImageCrop.jpg
modified: '2016-10-13T14:10:59'
published: '2016-10-13T11:53:13'
tags: []
thumbnail: images/DM16AngelSq_MainImageCrop_thumb.jpg
title: DesignMcr @ Manchester CoderDojo Creative Brief
