author: Tom Clarke
cover_image: DM16AngelSq_MainImageCrop.jpg
modified: '2016-10-13T14:10:59'
published: '2016-10-13T11:53:13'
slug: designmcr-manchester-coderdojo
tags: []
title: DesignMcr @ Manchester CoderDojo Creative Brief
