author: Steven Flower
cover_image: images/mcrcoderdojo-post-its.webp
modified: '2014-05-17T17:20:53'
published: '2013-12-21T08:43:10'
tags: []
thumbnail: images/mcrcoderdojo-post-its_thumb.webp
title: What Do We Want?
