author: DJ Adams
cover_image: images/jt1.jpg
modified: '2014-05-17T17:20:53'
published: '2013-12-17T14:56:12'
tags:
- game
- hardware
- makeymakey
- music
- scratch
thumbnail: images/jt1_thumb.jpg
title: Jingle Tangerines!
