cover_image: images/adamanchester-1038x576.png
modified: '2022-06-12T00:00:00'
published: '2022-06-12T00:00:00'
tags:
- events
thumbnail: images/adamanchester-1038x576_thumb.png
title: '#60: June 12th 2022'
