cover_image: images/panoram-1024x576.webp
modified: '2015-05-10T00:00:00'
published: '2015-05-10T00:00:00'
tags:
- events
thumbnail: images/panoram-1024x576_thumb.webp
title: '#22: Sunday 10th May 2015'
