cover_image: images/Mcr-Coderdojo-12_22-small-986x576.webp
modified: '2015-12-13T00:00:00'
published: '2015-12-13T00:00:00'
tags:
- events
thumbnail: images/Mcr-Coderdojo-12_22-small-986x576_thumb.webp
title: '#28: 13th December 2015'
