cover_image: images/MCRCODERDOJO-13-PHOTO-08-1038x576.webp
modified: '2015-03-08T00:00:00'
published: '2015-03-08T00:00:00'
tags:
- events
thumbnail: images/MCRCODERDOJO-13-PHOTO-08-1038x576_thumb.webp
title: '#21: Sunday 8th March 2015'
