author: Michelle Hua
cover_image: NTM-Hackathon-1.jpg
modified: '2015-10-21T22:33:41'
published: '2015-10-21T18:02:15'
slug: how-i-won-my-first-ever-hackathon
tags: []
title: How I won my first ever hackathon!
