cover_image: Coderdojo_062_smaller.jpg
modified: '2019-12-08T00:00:00'
published: '2019-12-08T00:00:00'
slug: 55-december-13th-2019-7th-birthday
tags:
- events
title: '#55: DECEMBER 8TH 2019 (7th Birthday!)'
