author: Anthony Harrison
cover_image: diceroller.png
modified: '2014-11-17T09:58:58'
published: '2014-11-09T18:21:01'
slug: using-appmaker-to-create-simple-apps
tags:
- appmaker
- mozilla
title: Using AppMaker to create simple Apps
