cover_image: images/Coderdojo_062_smaller.jpg
modified: '2019-12-08T00:00:00'
published: '2019-12-08T00:00:00'
tags:
- events
thumbnail: images/Coderdojo_062_smaller_thumb.jpg
title: '#55: DECEMBER 8TH 2019 (7th Birthday!)'
