cover_image: images/hackmanchesterjnr-1038x331.webp
modified: '2015-10-26T00:00:00'
published: '2015-10-26T00:00:00'
tags:
- events
thumbnail: images/hackmanchesterjnr-1038x331_thumb.webp
title: Hack Manchester Jnr
