author: Chris Mills
cover_image: code.png
modified: '2014-05-17T17:20:35'
published: '2014-02-13T13:37:06'
slug: learning-to-code-and-build-the-web-theres-never-been-a-better-time
tags:
- code
- learning
- web
title: 'Learning to code and build the Web: there&#8217;s never been a better time!'
