author: Steven Flower
cover_image: images/medals1.jpg
modified: '2015-10-17T10:36:12'
published: '2015-10-16T21:23:06'
tags: []
thumbnail: images/medals1_thumb.jpg
title: Countdown to HackManchester Jnr&#8230;
