author: Dave Mee
modified: '2014-09-15T14:01:20'
published: '2014-09-13T23:31:45'
slug: coding-for-kids-ipads-iphones-ipods-part-1
tags:
- coding
- hopscotch
- ipad
- iphone
- ipod
- kids
- review
- scratchjr
title: 'Coding for Kids: iPads, iPhones, iPods (part 1)'
