cover_image: images/eveningnews-1038x576.jpg
modified: '2015-07-12T00:00:00'
published: '2015-07-12T00:00:00'
tags:
- events
thumbnail: images/eveningnews-1038x576_thumb.jpg
title: '#24: Sunday 12th July 2015'
