author: Anthony Harrison
cover_image: images/diceroller.png
modified: '2014-11-17T09:58:58'
published: '2014-11-09T18:21:01'
tags:
- appmaker
- mozilla
thumbnail: images/diceroller_thumb.png
title: Using AppMaker to create simple Apps
