cover_image: images/Mcr-Coderdojo-12_22-small-986x576.jpg
modified: '2017-12-10T00:00:00'
published: '2017-12-10T00:00:00'
tags:
- events
thumbnail: images/Mcr-Coderdojo-12_22-small-986x576_thumb.jpg
title: '#43: December 10th 2017'
