cover_image: images/Manchester_Technology_Centre_Oxford_Road-1-1024x576.webp
modified: '2022-05-08T00:00:00'
published: '2022-05-08T00:00:00'
tags:
- events
thumbnail: images/Manchester_Technology_Centre_Oxford_Road-1-1024x576_thumb.webp
title: '#59: May 8th 2022'
