cover_image: images/MCRCODERDOJO-13-PHOTO-08-1038x576.webp
modified: '2014-10-12T00:00:00'
published: '2014-10-12T00:00:00'
tags:
- events
thumbnail: images/MCRCODERDOJO-13-PHOTO-08-1038x576_thumb.webp
title: '#17: October 2014'
