author: Steven Flower
cover_image: images/CODERDOJO-16-THE-SHARP-PROJECT-02.webp
modified: '2014-09-14T21:16:48'
published: '2014-09-14T21:13:04'
tags: []
thumbnail: images/CODERDOJO-16-THE-SHARP-PROJECT-02_thumb.webp
title: Activate
