author: Lisa Brown
cover_image: DSC06736-2.jpg
modified: '2023-04-09T16:35:14'
published: '2023-04-09T16:35:14'
slug: reflecting-on-10-years-of-manchester-coderdojo
tags: []
title: Reflecting on 10 Years of Manchester CoderDojo
