author: DJ Adams
cover_image: Screen-Shot-2014-05-11-at-18.46.24.png
modified: '2014-05-17T17:20:35'
published: '2014-05-11T18:23:14'
slug: scratch-python-and-google-apps-script
tags:
- googleappsscript
- python
- rubegoldberg
- scratch
title: Scratch, Python and Google Apps Script
