cover_image: images/MCRCODERDOJO-13-PHOTO-08-1038x576.jpg
modified: '2014-09-14T00:00:00'
published: '2014-09-14T00:00:00'
tags:
- events
thumbnail: images/MCRCODERDOJO-13-PHOTO-08-1038x576_thumb.jpg
title: '#16: September 2014'
